version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-cli: circleci/aws-cli@1.2.1
  win: circleci/windows@2.4.0

executors:
  default:
    machine:
      docker_layer_caching: true
  macos:
    macos:
      xcode: "11.5"

jobs:
  add-ssh-keys:
    executor: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6a:38:0c:b2:8b:c8:e9:46:97:b0:df:b4:5b:df:ff:54"
  build-and-push-unity-image:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker
      - aws-ecr/build-image:
          repo: $CIRCLE_PROJECT_REPONAME
          tag: "git-$CIRCLE_SHA1"
          extra-build-args: >-
            --build-arg ulf="$ULF"
            --build-arg prior_dlls="git-$CIRCLE_SHA1"
      - aws-cli/install
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: $CIRCLE_PROJECT_REPONAME
          tag: "git-$CIRCLE_SHA1"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - add-ssh-keys
      - build-and-push-unity-image:
          requires:
            - add-ssh-keys