name: main

on:
  push:
    branches: []
    tags: []
  pull_request:
    branches: []

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Check if .Libplanet refers to a tagged commit
      if: |
        github.event_name == 'push' && (
          github.ref == 'refs/heads/main' ||
          startsWith(github.ref, 'refs/heads/rc-') ||
          startsWith(github.ref, 'refs/tags/')
        ) ||
        github.event_name == 'pull_request' && (
          github.head_ref == 'refs/heads/main' ||
          startsWith(github.head_ref, 'refs/heads/rc-') ||
          startsWith(github.head_ref, 'refs/tags/')
        )
      run: |
        set -e
        pushd .Libplanet/
        git fetch origin 'refs/tags/*:refs/tags/*'
        if ! git describe --tags --exact-match; then
          echo "The unreleased Libplanet shouldn't be used." > /dev/stderr
          exit 1
        fi
        popd
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  release:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Check if a new tag refers a merge commit
      if: github.ref_type == 'tag'
      run: |
        set -evx
        curl -o /tmp/web-flow.gpg "$WEB_FLOW_KEY_URL"
        gpg --import /tmp/web-flow.gpg
        if ! git verify-commit "$GITHUB_REF_NAME" && \
           [[ "$( git cat-file -p "$GITHUB_REF_NAME" \
                | grep -Ei '^parent\s+[0-9a-f]{40}$' | wc -l )" -lt 2 ]]; then
          echo "::error title=Invalid tag commit::Tags must refer to a merge" \
               "commit or a commit signed by GitHub web-flow" \
               "($WEB_FLOW_KEY_URL).  The tag $GITHUB_REF_NAME refers to " \
               "a commit $(git rev-parse $GITHUB_REF_NAME) which is neither" \
               "a merge commit nor signed by GitHub web-flow."
          exit 1
        fi
      env:
        WEB_FLOW_KEY_URL: https://github.com/web-flow.gpg
    - name: Update other repos referring lib9c as submodules
      uses: planetarium/submodule-updater@main
      with:
        token: ${{ secrets.SUBMODULE_UPDATER_GH_TOKEN }}
        committer: >
          Submodule Updater <engineering+submodule-updater@planetariumhq.com>
        targets: |
          ${{ github.repository_owner }}/NineChronicles:rc-${{ github.ref_name }}?
          ${{ github.repository_owner }}/NineChronicles.Headless:rc-${{ github.ref_name }}?
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.100
    - name: Collect available action type ids
      run: |
        mkdir publish
        dotnet run --project .Lib9c.Tools/Lib9c.Tools.csproj -- action list > publish/all_action_type_ids.txt
    - name: Publish available action type ids
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
        destination_dir: ${{ github.ref_name }}

  update-submodule:
    if: github.ref_type == 'branch' && startsWith(github.ref_name, 'rc-v')
    runs-on: ubuntu-latest
    steps:
    - name: Update other repos referring lib9c as submodules
      uses: planetarium/submodule-updater@main
      with:
        token: ${{ secrets.SUBMODULE_UPDATER_GH_TOKEN }}
        committer: >
          Submodule Updater <engineering+submodule-updater@planetariumhq.com>
        targets: |
          ${{ github.repository_owner }}/NineChronicles:${{ github.ref_name }}?
          ${{ github.repository_owner }}/NineChronicles.Headless:${{ github.ref_name }}?
