name: release
on:
  push:
    tags:
    - v*
    branches:
    - rc-v*

jobs:
  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check if a new tag refers a merge commit
      run: |
        set -evx
        curl -o /tmp/web-flow.gpg "$WEB_FLOW_KEY_URL"
        gpg --import /tmp/web-flow.gpg
        if ! git verify-commit "$GITHUB_REF_NAME" && \
           [[ "$( git cat-file -p "$GITHUB_REF_NAME" \
                | grep -Ei '^parent\s+[0-9a-f]{40}$' | wc -l )" -lt 2 ]]; then
          echo "::error title=Invalid tag commit::Tags must refer to a merge" \
               "commit or a commit signed by GitHub web-flow" \
               "($WEB_FLOW_KEY_URL).  The tag $GITHUB_REF_NAME refers to " \
               "a commit $(git rev-parse $GITHUB_REF_NAME) which is neither" \
               "a merge commit nor signed by GitHub web-flow."
          exit 1
        fi
      env:
        WEB_FLOW_KEY_URL: https://github.com/web-flow.gpg
